/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all notes for current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of notes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Note"][];
          };
        };
        401: components["responses"]["UnauthorizedError"];
      };
    };
    put?: never;
    /** Create a new note */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateNote"];
        };
      };
      responses: {
        /** @description Note created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Note"];
          };
        };
        401: components["responses"]["UnauthorizedError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notes/{noteId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Edit a note */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          noteId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["EditNote"];
        };
      };
      responses: {
        /** @description Note updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Note"];
          };
        };
        401: components["responses"]["UnauthorizedError"];
        404: components["responses"]["NotFoundError"];
      };
    };
    post?: never;
    /** Delete a note */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          noteId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Note deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components["responses"]["UnauthorizedError"];
        404: components["responses"]["NotFoundError"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Note: {
      id: string;
      title: string;
      content: string;
    };
    Error: {
      message: string;
      code: string;
    };
    CreateNote: {
      title: string;
      content: string;
    };
    EditNote: {
      title: string;
      content: string;
    };
  };
  responses: {
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource not found */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
