openapi: 3.0.0
info:
  title: Notes API
  description: Notes API
  version: 1.0.0
paths:
  /notes:
    get:
      $ref: "./endpoints/notes.yaml#/getAllNotes"

    post:
      $ref: "./endpoints/notes.yaml#/createNote"

  /notes/{noteId}:
    delete:
      $ref: "./endpoints/notes.yaml#/deleteNote"

    put:
      $ref: "./endpoints/notes.yaml#/editNote"
